### PR TITLE
feat: Fix geolocation (Primarily for timezone detection) now that Mozilla has exited

### LINKED ISSUE #2203: Configure geoclue to use beacondb
We can't set timezones automatically due to mozilla's geoclue service not existing. There's an alternative: 

https://fedoramagazine.org/the-state-of-the-location-permission-on-fedora-linux-in-2025/

IMO we should set this up for bluefin and bazzite's gnome images so geoclue works.

### PR DESCRIPTION
**Pull request by KyleGospo**
Fixes #2203

### CODE REVIEW

**Comment by castrojo** [comment]
+1, let's see how it works in bazzite's testing branch. Thanks!

File: system_files/shared/etc/geoclue/conf.d/99-beacondb.conf [hunk 1]
```diff
@@ -0,0 +1,3 @@
+[wifi]
+enable=true
+url=https://api.beacondb.net/v1/geolocate
```
Comment (jplock) [inline system_files/shared/etc/geoclue/conf.d/99-beacondb.conf:3]: Is this a valid URL?

```
curl https://api.beacondb.net/v1/geolocate -i
HTTP/2 404 
server: nginx
date: Wed, 12 Feb 2025 23:50:58 GMT
content-length: 0
```

Comment (KyleGospo) [reply system_files/shared/etc/geoclue/conf.d/99-beacondb.conf:3]: It should be, this entire thing is from the Fedora magazine.

Comment (p5) [reply system_files/shared/etc/geoclue/conf.d/99-beacondb.conf:3]: It works using a POST request.  GETs return a 404
