### PR TITLE
fix: ensure gnome-extensions-app is removed

### LINKED ISSUE #1712: GNOME extensions app is not removed
image

We explicitly remove this in packages.json but it still shows up in the menu and exists on the image. We need to nuke this thing from orbit, it's the only way to be sure.

### PR DESCRIPTION
**Pull request by p5**
Closes #1712

### CODE REVIEW

File: build_files/packages-dx.sh [hunk 1]
```diff
@@ -39,14 +39,16 @@ else
     echo "No packages to install."
 fi
 
-# check if any excluded packages are still present
+NEWLY_ADDED_PACKAGES_TO_EXCLUDE=()
```
Comment (p5) [inline build_files/packages-dx.sh:42]: Naming things is hard

File: build_files/packages-dx.sh [hunk 2]
```diff
@@ -20,20 +20,23 @@ EXCLUDED_PACKAGES=($(jq -r "[(.all.exclude | (select(.all != null).all)[]), \
                     (select(.\"$FEDORA_MAJOR_VERSION\" != null).\"$FEDORA_MAJOR_VERSION\".exclude | (select(.dx != null).dx)[])] \
                     | sort | unique[]" /tmp/packages.json))
 
+# store a list of RPMs installed on the image
+INSTALLED_EXCLUDED_PACKAGES=()
+
 # ensure exclusion list only contains packages already present on image
 if [[ "${#EXCLUDED_PACKAGES[@]}" -gt 0 ]]; then
-    EXCLUDED_PACKAGES=($(rpm -qa --queryformat='%{NAME} ' ${EXCLUDED_PACKAGES[@]}))
```
Comment (p5) [inline build_files/packages-dx.sh:25]: The list of EXCLUDED_PACKAGES is being overwritten here to be only those installed on the image before installing any packages (therefore does not include gnome-extensions-app).

**Review by castrojo — APPROVED** [review]
