### PR TITLE
fix(flatpak): Remove Fedora Flatpak remote

### LINKED ISSUE #2288: Remove Fedora Flatpak remote
Proposal to remove the Fedora flaptak remote so that we only have Flathub:

```
sudo flatpak remote-delete fedora-testing 
sudo flatpak remote-delete fedora
```

idk if this will break existing installations. If so maybe we can look into some migration

- [ ] See if existing Fedora flatpaks will keep working if the fedora remote is removed
- [ ] If it does, see if migrating Fedora flatpaks to flathub ones or add the fedora remote back for users that already have fedora flatpaks

### PR DESCRIPTION
**Pull request by hanthor**
Fixes #2288

This will add the flathub remote and remove the Fedora one's. The flathub remote is added to ISOs but not if the uer installs via bootc-install

### CODE REVIEW

**Review by castrojo — APPROVED** [review]

**Review by tulilirockz — DISMISSED** [review]
Looks fine? Not particularly sure if this works tho

**Review by p5 — APPROVED** [review]

File: build_files/base/17-cleanup.sh [hunk 1]
```diff
@@ -34,6 +34,15 @@ for file in fish htop nvtop; do
     fi
 done
 
+
+#Disable autostart behaviour
+rm -f /etc/xdg/autostart/solaar.desktop
+
+#Add the Flathub Flatpak remote and remove the Fedora Flatpak remote
+flatpak remote-delete --system fedora
```
Comment (p5) [inline build_files/base/17-cleanup.sh:42]:
```suggestion
```

**Review by p5 — APPROVED** [review]
